### PR TITLE
Bug fix for NullPointerException Error at LoginFragment

### PR DESCRIPTION
**Pull request by BernaTasel**
Fixed error when trying to login while textfields are null.

Complete with the least possible changes with your suggestion.

### CODE REVIEW

**Review by safaorhan — APPROVED** [review]
💯

**Comment by turkergoksu** [comment]
I manage to get all of the available error messages inside Validator classes and logged in successfully. Looks like it's fixed. Claps @BernaTasel 👏

**Comment by bariscankurt** [comment]
I checked required control cases and everything is working as expected. Congrats 👏

**Comment by safaorhan** [comment]
Thanks to all of you folks!

**Pull request merged**
